version: "3"

services:
  mariadb:
    image: "${DATABASE_TAG}"
    restart: "always"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "mariadb"
    networks:
      - internal

  api:
    depends_on:
      - mariadb
    build: "${API_TAG}"
    ports:
      - "8081:8081"
    restart: "always"
    environment:
      - "SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:3306/mariadb"
      - "SPRING_DATASOURCE_USERNAME=root"
      - "SPRING_DATASOURCE_PASSWORD=root"
      - "SPRING_JPA_HIBERNATE_DDL-AUTO=create"
      - "SERVER_PORT=8081"
    networks:
      - internal

  ui:
    depends_on:
      - api
    build: "${UI_TAG}"
    ports:
      - "3000:3000"
    restart: "on-failure"
    networks:
      - internal

  postgres:
    image: postgres:13.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRESQL_DB}
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASS}
    networks:
      - internal

  keycloak:
    depends_on:
      - postgres
    image: jboss/keycloak:${KEYCLOAK_VERSION}
    ports:
      - "28080:8080"
    restart: "unless-stopped"
    environment:
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_DATABASE: ${POSTGRESQL_DB}
      DB_USER: ${POSTGRESQL_USER}
      DB_PASSWORD: ${POSTGRESQL_PASS}
    container_name: local_keycloak
    networks:
      - internal

  mailhog:
    image: "mailhog/mailhog:v1.0.1"
    ports:
      - "50007:8025"
    networks:
      - internal

networks:
  internal:
    external: false